### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by megoRU** [megoRU/GiveawayDiscordBot#117]
```
java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.entities.Guild.getTextChannelById(long)" because the return value of "net.dv8tion.jda.api.JDA.getGuildById(long)" is null
        at main.config.BotStartConfig.updateUserList(BotStartConfig.java:394)
        at jdk.internal.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by megoRU** [comment]
Fixed

issues: https://github.com/megoRU/GiveawayDiscordBot/blob/b095179f1d10bac0af6540e5c3fcf5ec86e37dca/src/main/java/main/config/BotStartConfig.java#L394
