### ISSUE TITLE
10008: Unknown Message

### ISSUE THREAD

**Issue by megoRU** [megoRU/GiveawayDiscordBot#125]
```
2022-07-26 04:27:18.847 ERROR 1 --- [onPool-worker-3] net.dv8tion.jda.api.requests.RestAction  : RestAction queue returned failure: [ErrorResponseException] 10008: Unknown Message

net.dv8tion.jda.api.exceptions.ContextException: null
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.internal.requests.restaction.operator.RestActionOperator.contextWrap(RestActionOperator.java:123) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.internal.requests.restaction.operator.FlatMapRestAction.queue(FlatMapRestAction.java:50) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:573) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:539) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at main.giveaway.Gift.startGift(Gift.java:203) ~[classes!/:0.0.1-SNAPSHOT]
        at main.giveaway.slash.SlashCommand.onSlashCommandInteraction(SlashCommand.java:121) ~[classes!/:0.0.1-SNAPSHOT]
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:382) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:169) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:109) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:80) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:954) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:841) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:819) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:993) ~[JDA-5.0.0-alpha.13.jar!/:5.0.0-alpha.13]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[nv-websocket-client-2.14.jar!/:na]

```

**Comment by megoRU** [comment]
https://github.com/megoRU/GiveawayDiscordBot/pull/136
