### ISSUE TITLE
java.lang.IllegalArgumentException: Message ID may not be null

### ISSUE THREAD

**Issue by megoRU** [megoRU/GiveawayDiscordBot#134]
```
java.lang.IllegalArgumentException: Message ID may not be null
	at net.dv8tion.jda.internal.utils.Checks.notNull(Checks.java:81)
	at net.dv8tion.jda.internal.utils.Checks.isSnowflake(Checks.java:51)
	at net.dv8tion.jda.api.entities.MessageChannel.retrieveMessageById(MessageChannel.java:837)
	at net.dv8tion.jda.internal.entities.mixin.channel.middleman.MessageChannelMixin.retrieveMessageById(MessageChannelMixin.java:175)
	at main.config.BotStartConfig.updateUserList(BotStartConfig.java:361)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by megoRU** [comment]
https://github.com/megoRU/GiveawayDiscordBot/pull/136
