### ISSUE TITLE
java.lang.IllegalArgumentException: description may not be null

### ISSUE THREAD

**Issue by megoRU** [megoRU/GiveawayDiscordBot#149]
```
java.lang.IllegalArgumentException: description may not be null
        at net.dv8tion.jda.internal.utils.Checks.notNull(Checks.java:81)
        at net.dv8tion.jda.api.EmbedBuilder.appendDescription(EmbedBuilder.java:362)
        at main.giveaway.Gift.extracted(Gift.java:137)
        at main.giveaway.Gift.startGift(Gift.java:204)
        at main.giveaway.slash.SlashCommand.onSlashCommandInteraction(SlashCommand.java:130)
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:382)
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:170)
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:109)
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:80)
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840)
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by megoRU** [comment]
Fixed in https://github.com/megoRU/GiveawayDiscordBot/commit/9de918bbdbe20c38ca219e6060bdbfd7ae1f13fb
