### ISSUE TITLE
No winners after completion

### ISSUE THREAD

**Issue by megoRU** [megoRU/GiveawayDiscordBot#15]
![image](https://user-images.githubusercontent.com/23276305/148558708-a6fda711-9971-4f93-9c34-7f28f20e7de4.png)

TODO:

- [x] Make protection against completion and deletion of the draw in case of connection error

```
Count winner: 4
java.net.ConnectException: Connection refused
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:551)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at main.giveaway.Gift.getWinners(Gift.java:276)
        at main.giveaway.Gift.stopGift(Gift.java:328)
        at main.threads.StopGiveawayByTimer.run(StopGiveawayByTimer.java:37)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectEvent.handle(PlainHttpConnection.java:128)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:956)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:911)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:911)
2022-02-12 11:47:48.465  INFO 1 --- [pool-1-thread-1] main.giveaway.Gift     

```

**Comment by megoRU** [comment]
Fix

**Comment by megoRU** [comment]
```
Count winner: 4
java.net.ConnectException: Connection refused
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:551)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at main.giveaway.Gift.getWinners(Gift.java:276)
        at main.giveaway.Gift.stopGift(Gift.java:328)
        at main.threads.StopGiveawayByTimer.run(StopGiveawayByTimer.java:37)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectEvent.handle(PlainHttpConnection.java:128)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:956)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:911)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:911)
2022-02-12 11:47:48.465  INFO 1 --- [pool-1-thread-1] main.giveaway.Gift     

```

TODO:

- [ ] Make protection against completion and deletion of the draw in case of connection error
