### ISSUE TITLE
Cannot perform action due to a lack of Permission. Missing permission: VIEW_CHANNEL

### ISSUE THREAD

**Issue by megoRU** [megoRU/GiveawayDiscordBot#159]
```
2022-08-22 20:58:36.426  INFO 1 --- [inWS-ReadThread] main.giveaway.Gift                       :
Guild id: 1009117729237782528
TextChannel: 🎩┃администрация 1009128893300613220
Title: null
Count winners: null
Time: null
Role: null
isOnlyForSpecificRole: false
urlImage: null
net.dv8tion.jda.api.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: VIEW_CHANNE                                                                                           L
        at net.dv8tion.jda.internal.entities.mixin.channel.middleman.GuildChannelMixin.checkPermission(GuildChannelMixin.java:63)
        at net.dv8tion.jda.internal.entities.mixin.channel.middleman.GuildChannelMixin.checkPermission(GuildChannelMixin.java:55)
        at net.dv8tion.jda.internal.entities.mixin.channel.middleman.GuildMessageChannelMixin.checkCanAccessChannel(GuildMessageChannelMixin.java:                                                                                           123)
        at net.dv8tion.jda.internal.entities.mixin.channel.middleman.MessageChannelMixin.sendMessageEmbeds(MessageChannelMixin.java:134)
        at main.giveaway.Gift.startGift(Gift.java:201)
        at main.giveaway.slash.SlashCommand.onSlashCommandInteraction(SlashCommand.java:159)
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:382)
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:170)
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:109)
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:80)
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840)
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
2022-08-22 20:58:36.426 ERROR 1 --- [inWS-ReadThread] net.dv8tion.jda.api.requests.RestAction  : RestAction queue returned failure

java.lang.IllegalStateException: This interaction has already been acknowledged or replied to. You can only reply or acknowledge an interaction on                                                                                           ce!
        at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.tryAck(InteractionCallbackImpl.java:124) ~[JDA-5.0.0-                                                                                           alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.queue(InteractionCallbackImpl.java:131) ~[JDA-5.0.0-a                                                                                           lpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:573) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:539) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at main.giveaway.slash.SlashCommand.onSlashCommandInteraction(SlashCommand.java:181) ~[classes!/:0.0.1-SNAPSHOT]
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:382) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:170) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:109) ~[JDA-5.0.0-alpha.17.jar!/:5.                                                                                           0.0-alpha.17]
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:80) ~[JDA-5.0.0-alpha.17.jar!/:                                                                                           5.0.0-alpha.17]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[nv-websocket-client-2.14.jar!/:na]

```

**Comment by megoRU** [comment]
Это происходит когда используется `/start` в том канале где нет прав
