### ISSUE TITLE
10008: Unknown Message

### ISSUE THREAD

**Issue by megoRU** [megoRU/GiveawayDiscordBot#171]
```
2022-08-31 10:18:45.915 ERROR 1 --- [onPool-worker-3] net.dv8tion.jda.api.requests.RestAction  : RestAction queue returned failure: [ErrorResponse                                                                                           Exception] 10008: Unknown Message

net.dv8tion.jda.api.exceptions.ContextException: null
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
        at net.dv8tion.jda.internal.requests.restaction.operator.RestActionOperator.contextWrap(RestActionOperator.java:123) ~[JDA-5.0.0-alpha.18.                                                                                           jar!/:5.0.0-alpha.18]
        at net.dv8tion.jda.internal.requests.restaction.operator.FlatMapRestAction.queue(FlatMapRestAction.java:50) ~[JDA-5.0.0-alpha.18.jar!/:5.0                                                                                           .0-alpha.18]
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
        at main.giveaway.Gift.startGift(Gift.java:212) ~[classes!/:0.0.1-SNAPSHOT]
        at main.giveaway.slash.SlashCommand.onSlashCommandInteraction(SlashCommand.java:172) ~[classes!/:0.0.1-SNAPSHOT]
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:382) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:170) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:109) ~[JDA-5.0.0-alpha.18.jar!/:5.                                                                                           0.0-alpha.18]
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:80) ~[JDA-5.0.0-alpha.18.jar!/:                                                                                           5.0.0-alpha.18]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:957) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:843) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:821) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:996) ~[JDA-5.0.0-alpha.18.jar!/:5.0.0-alpha.18]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[nv-websocket-client-2.14.jar!/:na]
```

**Comment by megoRU** [comment]
#172
