### ISSUE TITLE
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask

### ISSUE THREAD

**Issue by megoRU** [megoRU/GiveawayDiscordBot#240]
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6be8e1e5[Not completed, task =ava.util.concurrent.Executors$RunnableAdapter@61a4ede5[Wrapped task = main.giveaway.Giveaway$StopGiveawayThread@42168e54]] rejected from java.util.concurrent.ThreadPoolExecut                                                                                           or@163fffbf[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
        at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:748)
        at main.giveaway.Giveaway.stopGiveaway(Giveaway.java:387)
        at main.giveaway.Giveaway$StopGiveawayThread$1.run(Giveaway.java:469)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
2022-12-14T18:09:26.358Z  INFO 1 --- [       Timer-35] main.giveaway.Giveaway                   :
stopGift method
Count winners: 1
```

**Comment by megoRU** [comment]
Fix in this commit: https://github.com/megoRU/GiveawayDiscordBot/commit/2e446629f5dd841d7c2b39dc78cf07a1c445c021
