### ISSUE TITLE
java.lang.Exception: listUsersHash.size(): 2 != participants.size(): 3

### ISSUE THREAD

**Issue by megoRU** [megoRU/GiveawayDiscordBot#242]
```
java.lang.Exception: listUsersHash.size(): 2 != participants.size(): 3
        at main.giveaway.Giveaway.getWinners(Giveaway.java:322)
        at main.giveaway.Giveaway.stopGiveaway(Giveaway.java:374)
        at main.threads.StopGiveawayByTimer.run(StopGiveawayByTimer.java:52)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
```

**Comment by megoRU** [comment]
Fix in this https://github.com/megoRU/GiveawayDiscordBot/pull/243
